[program:eznet-thales-lb-inbound-2]
command=/usr/lib/jvm/temurin-25-jdk-arm64/bin/java
    -Xms128m -Xmx384m
    -Djava.awt.headless=true
    -Dsun.net.http.allowRestrictedHeaders=true
    -Djava.io.tmpdir=/data1/xenticate/hsm-lb/eznet-inbound-2/tmp
    -Deznet.root=/data1/xenticate/hsm-lb/eznet-inbound-2
    -Deznet.config.path=/data1/xenticate/hsm-lb/eznet-inbound-2/config
    -Deznet.log.path=/var/log/xenticate
    -jar /data1/xenticate/hsm-lb/bin/eznet-tcp2jms.war

environment=JAVA_HOME="/usr/lib/jvm/temurin-25-jdk-arm64"
directory=/data1/xenticate/hsm-lb/eznet-inbound-2
user=xenticate
autostart=true
autorestart=true
startretries=5
startsecs=10
stopwaitsecs=30
redirect_stderr=false
stdout_logfile=/var/log/xenticate/thales-lb-inbound2.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/log/xenticate/thales-lb-inbound2-err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
