[program:thales-lb2]
command=/usr/lib/jvm/temurin-25-jdk-arm64/bin/java
    -Xms256m -Xmx512m
    -Djava.awt.headless=true
    -Dlog4j2.configurationFile=/home/xenticate/thales-transparent-lb/deploy/config/log4j2.xml
    -jar /home/xenticate/thales-transparent-lb/target/thales-transparent-lb.jar
    --spring.config.location=/home/xenticate/thales-transparent-lb/deploy/lb-2/application.properties

environment=JAVA_HOME="/usr/lib/jvm/temurin-25-jdk-arm64"
directory=/home/xenticate/thales-transparent-lb
user=xenticate
autostart=true
autorestart=true
startretries=5
startsecs=15
stopwaitsecs=30
redirect_stderr=false
stdout_logfile=/var/log/xenticate/thales-lb2.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
stderr_logfile=/var/log/xenticate/thales-lb2-err.log
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=5
